### ISSUE TITLE
Add a function to get the version number

### ISSUE THREAD

**Issue by arthaud** [antoinemine/apron#14]
Could you please add a function that returns the version of APRON?

That would be similar to `gmp_version`, `mpfr_get_version`, `ppl_version`, etc.

Thanks!

**Comment by antoinemine** [comment]
PR #20 adds support for some macros (in C) and functions (in OCaml) to get the current APRON version.
What do you think ?

I'd like to switch back from a date-base version numbering to a more classic major.minor.micro versioning scheme, starting back at 0.9.11. However, I don't how this change will work for opam  (cf. PR #13 and https://opam.ocaml.org/doc/Manual.html#version-ordering)...

**Comment by arthaud** [comment]
Thank you, that's perfect.

I can't tell about opam, I'm not familiar with it.

**Comment by antoinemine** [comment]
OK, merged!

**Comment by nberth** [comment]
> I'd like to switch back from a date-base version numbering to a more classic major.minor.micro versioning scheme, starting back at 0.9.11. However, I don't how this change will work for opam (cf. PR #13 and https://opam.ocaml.org/doc/Manual.html#version-ordering)...

@antoinemine Indeed that could be an issue now that dates have been used for versioning packages in OPAM. I see two simple ways of handling this: (1) using the classic versioning scheme and removing or disabling date-based versions from OPAM (that would probably be ok since no new dependencies have been introduced I think); (2) prefixing the major number with a letter, e.g. v0.9.11. Packages from Jane Street are versioned according to this scheme I think.
