### ISSUE TITLE
sat_tcons wrong behaviour

### ISSUE THREAD

**Issue by ghilesZ** [antoinemine/apron#31]
If I understand the documentation correctly, when ```sat_tcons abs c``` returns true then all the values of the concretization of ```abs``` do satisfy the constraint ```c```. However, I stumbled upon examples with polyhedra, and a non-linear constraint, where ```sat_tcons``` answers ```true``` while some values of \gamma(abs) do not satisfy the constraint. The following code illustrates this behaviour:

```OCaml open Apron

let _ =
  let vx = Var.of_string "x" in
  let env = Environment.make [||] [|vx|] in

  (* x^2 - 2 >= 0*)
  let c = Coeff.s_of_int 2 in
  let x2 = Texpr1.(Binop(Pow,Var vx,Cst c,Real,Near)) in
  let sum' = Texpr1.(Binop(Sub,x2,Cst c,Real,Near)) in
  let texpr = Texpr1.of_expr env sum' in
  let cons = Tcons1.make texpr Lincons0.SUPEQ in

  (* x \in [-3;3] *)
  let pman = Polka.manager_alloc_strict() in
  let poly = Abstract1.top pman env in
  let texpr = Texpr1.cst env (Coeff.i_of_int (-3) 3) in
  let poly = Abstract1.assign_texpr pman poly vx texpr None in

  (* for x=0  'cons' is not satisfied, we should have false? *)
  Format.printf "does %a satisfy the constraint '%a'?\n%b\n%!"
    Abstract1.print poly Tcons1.print cons
    (Abstract1.sat_tcons pman poly cons)
```

**Comment by antoinemine** [comment]
Sorry for the long delay...

Indeed, this is a problem. It should return `true` only if it is certain that all concrete points in the abstract element satisfy the constraint, and `false` otherwise. There was an issue where an unsat check used internally overwrote an interval from the constraint. Hopefully, PR #85 fixes the issue and makes the example work as intended.

What do you think ?

**Comment by ghilesZ** [comment]
Thanks! this looks correct, i have not tested it yet but i think you can close the issue

**Comment by antoinemine** [comment]
OK, thanks!
