### ISSUE TITLE
Cannot find ap_ppl.h after installation [MacOS]

### ISSUE THREAD

**Issue by ForeverZyh** [antoinemine/apron#36]
Hi all,

After installing Apron, I cannot find ap_ppl.h in the target include directory. Here are the HAS Flags:
```
######################################################################
# HAS Flags
######################################################################

# If defined to non-empty value, generates dynamic libraries.
# Do not forget to add -fPIC to CFLAGS and CFLAGS_DEBUG
HAS_SHARED=1

# If defined to non-empty value, compiles the OCaml interface (bytecode)
# HAS_OCAML = 1
# If defined to non-empty value, compiles the OCaml interface (native code)
# HAS_OCAMLOPT = 1

# If defined to non-empty value, compiles the C++ interface (beta version)
# HAS_CPP = 1

# If defined to non-empty value, compiles the PPL domain
# (require included patch to PPL, see ppl/README and ppl/ppl.patch)

# HAS_PPL = 1

# If defined to non-empty value, compiles the fppol domain
# (The fppol domain requires GLPK)

# HAS_GLPK = 1

# If defined to non-empty value, support for "long double" is enabled

# HAS_LONG_DOUBLE = 1

# If defined to non-empty value, compiles the Java interface
# HAS_JAVA = 1

# If defined to non-empty value, assumed to be the right executable,
# use FINDLIB/ocamlfind package system
# (advised)
OCAMLFIND = ocamlfind
```

I additionally comment out `HAS_OCAML` and `HAS_OCAMLOPT` because I do not need ocaml API. In the https://github.com/antoinemine/apron/blob/master/README.mac, it says one should disable `HAS_PPL`, I suspect that we should keep this flag?

Actually, I find `ap_ppl.h` after setting `HAS_PPL=1`.

**Comment by antoinemine** [comment]
You need `HAS_PPL=1` to have PPL support compiled in and `ap_ppl.h` installed; otherwise, it is not installed.

The MacOS X instruction are not up to date and I have no way to support MacOS X at the moment. If you confirm that using `HAS_PPL=1` works, then I can update the `README.mac`.

That said, the preferred way to configure Apron is using the `configure` script, not writing a `Makefile.config` by hand. Ideally, we should update it to work on MacOS X as well. Can you tell me if it works out of the box or if there are errors with it?

**Comment by ForeverZyh** [comment]
Thanks, I can confirm that 
1. Using `configure` script is a better approach and it works on my PC.
2. Using `HAS_PPL=1` works on my PC.
