### ISSUE TITLE
cosine benchmark

### ISSUE THREAD

**Issue by cxyang1997** [antoinemine/apron#39]
to use cosine in this tool, do you first manually convert it into a Taylor expansion or this tool automatically convert that?

**Comment by antoinemine** [comment]
Cosine is not supported natively in Apron. You can indeed build by hand an expression that approximates cosine using Taylor expansion, or other methods. However, keep in mind that, due to the abstractions performed by most domains, such expressions are not likely to be analyzed precisely. If your domain is small, another possibility would be to provide a piecewise linear approximation of the function. If precision is not critical, you can use an interval, even [-1,1], in place of cosine.

**Comment by cxyang1997** [comment]
got it, thanks for the answer!
