### ISSUE TITLE
Build OCaml opam package without C++ and Java

### ISSUE THREAD

**Issue by sim642** [antoinemine/apron#40]
I've noticed random GitHub CI failures on our OCaml project caused by the Apron opam package failing to fully build, for example: https://github.com/goblint/analyzer/runs/3479696196?check_suite_focus=true#step:5:1326.
However that obscure failure is just from building the Java API, which isn't really necessary for the opam package.

It seems to me that the build instructions in `apron.opam` should simply specify `-no-cxx` and `-no-java` because even if the configure script determines their requirements met, it's not really necessary to build them when trying to install the opam package. It would avoid build failures unrelated to the OCaml API and maybe save a fraction of a second as well.

If one wants to use the C++ or Java API, then one would build Apron manually for that instead of through OCaml's opam package manager and then using the libraries from some opam's internal build directory.

**Comment by antoinemine** [comment]
I'd rather we fixed the issue rather than hiding it by not compiling the Java support even when Java is installed. It is actually quite convenient when you use OCaml as well as other languages (such as Java) to have a single installation method that works for all cases. Saving a fraction of a second is not really so useful.

Due to the randomness of the failure and the fact that you run `make -j2`, one possible explanation is a missing dependency that causes make to parallelize the build when it should not. Recent commit c852ebcc89e5cf4a5a3318e7c13c73e1756abb11 fixes one such issue and may help.
I intend to do a new release of Apron soon (with associated opam package). We'll see if it improves the situation.

**Comment by sim642** [comment]
> I can already opam pin the unreleased fix commit for our builds to see if this problem seems to go away.

I think we haven't seen this issue for two months anymore, so seems like that fixed it indeed.


> I intend to do a new release of Apron soon (with associated opam package). We'll see if it improves the situation.

How about that release then?

**Comment by antoinemine** [comment]
OK, nice to know it's working. I'll make a release after reviewing the pending PR and issues.
