### ISSUE TITLE
Floating point numbers using Polka manager

### ISSUE THREAD

**Issue by armandlego** [antoinemine/apron#50]
According to the documentation, the Polka manager doesn't handle floating point representation and instead convert floats to rationals :
> All scalars of type double are converted to scalars of type mpq_t inside NewPolka, as NewPolka works internally with exact rational arithmetics. So when possible it is better for the user (in term of efficiency) to convert already double scalars to mpq_t scalars. 
[Source](https://antoinemine.github.io/Apron/doc/api/c/NewPolka.html#NewPolka)

Is there an efficient way to ensure that computations, such as the getBound method, yield only conservative approximations of concrete operations, both for 32bits and 64bits floating points numbers ?

**Comment by antoinemine** [comment]
All the internal computations in Polka are done with rationals and require exact arithmetic not only to be sound, but also correct. Float arguments will always be converted to rationals in order to run the algorithms required by the domain (such as Chernikova). Also, allowing getBound to return only conservative float overapproximations would only mean that the exact rational result is converted to float just before returning, with no efficiency benefit wrt. doing the conversion in the client code after returning.

There is an experimental domain, called fppol, that implements polyhedra purely with floats, with sound but conservative approximations. It uses quite different algorithms than Polka to pull this off. However, it is less tested and less tuned than Polka.
